In [35]:
import pandas as pd
import numpy as np
import pickle

In [36]:
X_train, X_test, y_train, y_test = pickle.load( open('Train_and_Test_local.pklz',"rb") ) 
pickle.load( open('df.pklz',"rb") ) 

target                                               text
0          2  From: psyrobtw@ubvmsd.cc.buffalo.edu (Robert W...
1          1  From: myless@vaxc.cc.monash.edu.au (Myles Stro...
2          2  Organization: Penn State University\nFrom: <DG...
3          0  From: jaeger@buphy.bu.edu (Gregg Jaeger)\nSubj...
4          1  From: thinman@netcom.com (Technically Sweet)\n...
5          2  From: psyrobtw@ubvmsb.cc.buffalo.edu (Robert W...
6          1  From: brian@porky.contex.com (Brian Love)\nSub...
7          2  Organization: City University of New York\nFro...
8          1  From: td@alice.att.com (Tom Duff)\nSubject: Re...
9          2  From: hall@boi.hp.com (Hal Leifson)\nSubject: ...
10         0  From: Nanci Ann Miller <nm0w+@andrew.cmu.edu>\...
11         2  Subject: Re: Albert Sabin\nFrom: rfox@charlie....
12         0  From: richard@harlqn.co.uk (Richard Brooksby)\...
13         0  From: darice@yoyo.cc.monash.edu.au (Fred Rice)...
14         1  From: dave.mikelson@almac.co.uk (Dave Mikelson...
15         2  Subject: Re: "lds" Rick's reply\nFrom: <ISSCCK...
16         2  From: pharvey@quack.kfu.com (Paul Harvey)\nSub...
17         1  From: geigel@seas.gwu.edu (Joseph Geigel)\nSub...
18         0  From: kmr4@po.CWRU.edu (Keith M. Ryan)\nSubjec...
19         2  From: moskowit@panix.com (Len Moskowitz)\nSubj...
20         2  From: halat@pooh.bears (Jim Halat)\nSubject: R...
21         2  From: ekr@kyle.eitech.com (Eric Rescorla)\nSub...
22         2  From: ds0007@medtronic.COM (Dale M. Skiba)\nSu...
23         1  From: sigma@rahul.net (Kevin Martin)\nSubject:...
24         0  From: chrisb@seachg.com (Chris Blask)\nSubject...
25         0  From: a137490@lehtori.cc.tut.fi (Aario Sami)\n...
26         1  From: ccraig@nmt.edu (Catherine Craig)\nSubjec...
27         0  From: MANDTBACKA@FINABO.ABO.FI (Mats Andtbacka...
28         0  From: bobs@thnext.mit.edu (Robert Singleton)\n...
29         2  From: brian@lpl.arizona.edu (Brian Ceccarelli ...
...      ...                                                ...
1411       1  From: rws2v@uvacs.cs.Virginia.EDU (Richard Sto...
1412       2  From: alizard@tweekco.uucp (A.Lizard)\nSubject...
1413       1  From: robert@cpuserver.acsc.com (Robert Grant)...
1414       2  From: mccullou@snake2.cs.wisc.edu (Mark McCull...
1415       0  From: mathew <mathew@mantis.co.uk>\nSubject: R...
1416       0  From: keith@cco.caltech.edu (Keith Allan Schne...
1417       0  Subject: Re: islamic authority over women\nFro...
1418       0  From: acooper@mac.cc.macalstr.edu\nSubject: Id...
1419       1  From: bbs.mirage@tsoft.net (Jerry Lee)\nSubjec...
1420       1  From: cst@garfield.catt.ncsu.edu (Caroline Tsa...
1421       1  From: rgc3679@bcstec.ca.boeing.com (Robert G. ...
1422       2  From: ece_0028@bigdog.engr.arizona.edu (David ...
1423       0  From: mangoe@cs.umd.edu (Charley Wingate)\nSub...
1424       2  Subject: Re: After 2000 years, can we say that...
1425       0  From: lucio@proxima.alt.za (Lucio de Re)\nSubj...
1426       0  From: keith@cco.caltech.edu (Keith Allan Schne...
1427       1  From: bryanw@rahul.net (Bryan Woodworth)\nSubj...
1428       1  From: cavalier@blkbox.COM (Bill Egan)\nSubject...
1429       0  From: dewey@risc.sps.mot.com (Dewey Henize)\nS...
1430       1  From: nerone@ccwf.cc.utexas.edu (Michael Neron...
1431       1  From: neideck@nestvx.enet.dec.com (Burkhard Ne...
1432       2  From: ece_0028@bigdog.engr.arizona.edu (David ...
1433       0  From: healta@saturn.wwc.edu (Tammy R Healy)\nS...
1434       1  From: teckjoo@iti.gov.sg (Chua Teck Joo)\nSubj...
1435       2  From: margoli@watson.ibm.com (Larry Margolis)\...
1436       1  From: rah13@cunixb.cc.columbia.edu (Robert A H...
1437       2  From: brian@lpl.arizona.edu (Brian Ceccarelli ...
1438       1  From: schwartz@ils.nwu.edu (diane schwartz)\nS...
1439       0  From: mathew <mathew@mantis.co.uk>\nSubject: R...
1440       2  From: kv07@IASTATE.EDU (Warren Vonroeschlaub)\...

[1441 rows x 2 columns]

### Feature engineering

In [37]:
from sklearn.feature_extraction import text as sk_text

In [38]:
type(X_train)

pandas.core.series.Series

In [39]:
X_train.shape

(1422,)

In [40]:
X_train.iloc[9]

'From: lancer@oconnor.WPI.EDU (Stephe Lewis Foskett)\nSubject: How do DI boxes work?\nOrganization: ZikZak Corporation\nLines: 19\nDistribution: world\nNNTP-Posting-Host: oconnor.wpi.edu\n\n\nI\'m doing sound for a couple of bands around here and we need Direct\nInput boxes for the keyboards.  These are the little boxes that take a\nline level out of the keyboard and transform it into low-Z for the run\nto the mixer.  Sadly they cost like $50 (or more) each and I\'m going\nto need like 5 or 10 of them!  I looked inside one (belonging to\nanother band) and it looks like just a transformer.  Does anyone have\nany plans for building them?  Perhaps in Anderton\'s "Electronic\nProjects for Musicians" book (which I am having a hell of a time\ntracking down...)?\n\nThanks a lot!\n\n.s.\n\nPS: Post or email.  I read this group...\n--\n- lancer@wpi.wpi.edu -                    - 0{{  MoDiMiDoFrSaSo: -\n-   Mein Kopf ist ein Labyrinth, mein Leben ist ein Minenfeld    -\n'

In [41]:
print(X_train[1433])

From: webb@itu1 (90-29265  Webber  AH)
Subject: Re: Adcom cheap products?
Organization: Rhodes University, Grahamstown, South Africa
X-Newsreader: TIN [version 1.1 PL8]
Lines: 52

Aaron Lung (alung@megatest.com) wrote:
: >I was also sceptical about the amps being built in the far-east
: >  or where-ever.  But if you look in the amp and see what components
: >  they use and how it was designed, you can easily see why the
: >  amplifiers sound so brilliant.

: Good point...also, I wouldn't be surprised that the components
: they use off-shore are of inferior quality.  As long as it was
: properly designed and robust, premium components are used, it
: shouldn't matter where it is assembled.

Definately, I agree wholeheartedly.  If they can build the amp where
  the labour is not so expensive, they can afford to put decent
  components in and go to more effort to improve the design of the
  amplifier - as Adcom has done.

: >I cannot see why people say the amplifier won't last - not with
:

### Bag of words

In [42]:
vectorizer = sk_text.CountVectorizer()
X_train_feat = vectorizer.fit_transform(X_train)

In [46]:
X_train_feat

<1422x28242 sparse matrix of type '<class 'numpy.longlong'>'
	with 217306 stored elements in Compressed Sparse Row format>

In [44]:
print(vectorizer.get_feature_names()[:10], '...', vectorizer.get_feature_names()[-10:])

['00', '000', '0000', '00000', '0000001200', '000062david42', '00014', '00041032', '0004136', '0004246'] ... ['zurbrin', 'zwaartepunten', 'zwak', 'zwakke', 'zware', 'zwarte', 'zz', '³ation', 'íålittin', 'ýé']


In [47]:
X_train_feat.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [21]:
X_train_feat.todense().shape

(1422, 28242)

In [17]:
print(X_train_feat.shape)

(1422, 28242)


In [18]:
print(np.max(X_train_feat.toarray()))

# how many times the word that appeared most is counted

336


In [48]:
X_train_feat.toarray()

(1422, 28242)

### Bag of chars

In [49]:
vectorizer = sk_text.CountVectorizer(analyzer='char')
X_train_feat = vectorizer.fit_transform(X_train)
print(X_train_feat.shape)
print(vectorizer.get_feature_names()[:10], '...', vectorizer.get_feature_names()[-10:])

(1422, 85)
['\x03', '\x06', '\x08', '\t', '\n', '\x1a', '\x1b', ' ', '!', '"'] ... ['~', '³', 'ß', 'å', 'é', 'í', '÷', 'û', 'ý', 'ÿ']


In [50]:
len(vectorizer.get_feature_names())

85

In [51]:
character_counts = pd.DataFrame(X_train_feat.todense(), 
                                columns = vectorizer.get_feature_names(),
                               index = X_train.index)
character_counts

      \t   \n             !   " ...    ~  ³  ß  å  é  í  ÷  û  ý  ÿ
1433  0  0  0   0   31  0  0   431   1   0 ...    0  0  0  0  0  0  0  0  0  0
967   0  0  0   0   23  0  0   248   0   2 ...    0  0  0  0  0  0  0  0  0  0
210   0  0  0   0   12  0  0    73   0   0 ...    0  0  0  0  0  0  0  0  0  0
1616  0  0  0   0   14  0  0   191   0   2 ...    0  0  0  0  0  0  0  0  0  0
445   0  0  0   0   14  0  0   142   0   0 ...    0  0  0  0  0  0  0  0  0  0
308   0  0  0   0   20  0  0   360   0  32 ...    0  0  0  0  0  0  0  0  0  0
1373  0  0  0   0   10  0  0    67   0   0 ...    0  0  0  0  0  0  0  0  0  0
824   0  0  0   0   28  0  0   252   0   0 ...    0  0  0  0  0  0  0  0  0  0
821   0  0  0   0    4  0  0    78   3   0 ...    0  0  0  0  0  0  0  0  0  0
398   0  0  0   0   17  0  0   140   2   2 ...    0  0  0  0  0  0  0  0  0  0
1261  0  0  0   0    9  0  0   194   0   2 ...    0  0  0  0  0  0  0  0  0  1
244   0  0  0   0   37  0  0   371   2   2 ...    0  0  0  0  0  0  0  0  0  0
1691  0  0  0   1    9  0  0    80   0   0 ...    0  0  0  0  0  0  0  0  0  0
165   0  0  0   0   22  0  0   347   0   0 ...    0  0  0  0  0  0  0  0  0  0
876   0  0  0   0   17  0  0   121   1   4 ...    0  0  0  0  0  0  0  0  0  0
211   0  0  0   0   22  0  0   243   3   0 ...    0  0  0  0  0  0  0  0  0  0
1702  0  0  0   0   11  0  0   114   1   0 ...    0  0  0  0  0  0  0  0  0  0
718   0  0  0   0   12  0  0   240   1   0 ...    0  0  0  0  0  0  0  0  0  0
219   0  0  0   0   27  0  0   685   0   4 ...    0  0  0  0  0  0  0  0  0  0
55    0  0  0   0   17  0  0   176   0   0 ...    0  0  0  0  0  0  0  0  0  0
174   0  0  0   0   23  0  0   171   5   0 ...    0  0  0  0  0  0  0  0  0  0
1706  0  0  0   0   23  0  0   245   1   6 ...    0  0  0  0  0  0  0  0  0  0
614   0  0  0   0   11  0  0   131   0   0 ...    0  0  0  0  0  0  0  0  0  0
638   0  0  0   0    4  0  0   166   0   0 ...    0  0  0  0  0  0  0  0  0  0
844   0  0  0   0   15  0  0    80   0   0 ...    0  0  0  0  0  0  0  0  0  0
351   0  0  0   0   26  0  0   285   0   2 ...    0  0  0  0  0  0  0  0  0  0
620   0  0  0   0   13  0  0   182   1   0 ...    0  0  0  0  0  0  0  0  0  0
950   0  0  0   0   10  0  0    64   0   0 ...    0  0  0  0  0  0  0  0  0  0
1066  0  0  0   0   17  0  0   303   0   0 ...    0  0  0  0  0  0  0  0  0  0
50    0  0  0   0   15  0  0   204   2   4 ...    0  0  0  0  0  0  0  0  0  0
...  .. .. ..  ..  ... .. ..   ...  ..  .. ...  ... .. .. .. .. .. .. .. .. ..
1006  0  0  0   0   17  0  0   169   0   0 ...    0  0  0  0  0  0  0  0  0  0
822   0  0  0   0   13  0  0   107   0   2 ...    0  0  0  0  0  0  0  0  0  0
577   0  0  0   0   23  0  0   320   0   6 ...    0  0  0  0  0  0  0  0  0  0
1679  0  0  0   0   15  1  0   244   0   2 ...    0  0  0  0  0  0  0  0  0  0
1499  0  0  0   1   17  0  0   173   0   2 ...    0  0  0  0  0  0  0  0  0  0
432   0  0  0   0    8  0  0    67   0   0 ...    0  0  0  0  0  0  0  0  0  0
1652  0  0  0   0   15  0  0   111   2   2 ...    0  0  0  0  0  0  0  0  0  0
789   0  0  0   0   16  0  0   197   0   2 ...    0  0  0  0  0  0  0  0  0  0
1308  0  0  0   0   15  0  0    99   0   0 ...    0  0  0  0  0  0  0  0  0  0
792   0  0  0   0   74  0  0   408   1  50 ...    0  0  0  0  0  0  0  0  0  0
375   0  0  0   2    7  0  0    57   0   4 ...    0  0  0  0  0  0  0  0  0  0
133   0  0  0   0   12  0  0   129   0   2 ...    0  0  0  0  0  0  0  0  0  0
690   0  0  0   0   11  0  0    58   0   0 ...    0  0  0  0  0  0  0  0  0  0
976   0  0  0   0   13  0  0   200   0   0 ...    0  0  0  0  0  0  0  0  0  0
12    0  0  0   0   23  0  0   209   2   0 ...    0  0  0  0  0  0  0  0  0  0
595   0  0  0   0   24  0  0   170   0   4 ...    0  0  0  0  0  0  0  0  0  0
1016  0  0  0   0   14  0  0   168   1   4 ...    0  0  0  0  0  0  0  0  0  0
1223  0  0  0   0   28  0  0  6113   1  42 ...    0  0  0  0  0  0  0  0  0  0
1200  0  0  0   0   37  0  0   393   3  14 ...    0  0  

### Bag of words cleaned

In [54]:
vectorizer = sk_text.CountVectorizer(min_df=10, 
                                     stop_words='english',
                                    token_pattern=r'\b[a-zA-Z]+\b')
X_train_feat = vectorizer.fit_transform(X_train)

In [53]:
print(vectorizer.get_feature_names()[:10], '...', vectorizer.get_feature_names()[-10:])

['aaron', 'ab', 'ability', 'able', 'absolutely', 'absurd', 'absurdities', 'ac', 'academic', 'accelerator'] ... ['york', 'young', 'z', 'zealand', 'zero', 'zeus', 'zinc', 'zisfein', 'zoo', 'zoology']


In [29]:
X_train_feat.shape

(1422, 2932)

In [30]:
X_train_feat.todense()

matrix([[1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [31]:
print(X_train_feat.shape)
print(np.max(X_train_feat.toarray()))

(1422, 2932)
102


### Bag of words cleaned with n-grams

In [32]:
vectorizer = sk_text.CountVectorizer(min_df=5, 
                                     stop_words='english',
                                    ngram_range=(1,3))
X_train_feat = vectorizer.fit_transform(X_train)

In [33]:
print(vectorizer.get_feature_names()[:10], '...', vectorizer.get_feature_names()[-10:])

['00', '00 00', '00 00 gmt', '00 gmt', '00 gmt lines', '00 p003228', '000', '000 000', '000 feet', '000 files'] ... ['zisfein factory com', 'zisfein lines', 'zisfein subject', 'zoo', 'zoo toronto', 'zoo toronto edu', 'zoology', 'zoology kipling', 'zoology kipling henry', 'zoology lines']


In [34]:
X_train_feat.shape

(1422, 11659)

In [35]:
X_train_feat.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
print(X_train_feat.shape)
print(np.max(X_train_feat.toarray()))

(1422, 11659)
102


#### Exercise 2: extract bag of words and bag of character features from the dataset

In [55]:
vectorizer = sk_text.CountVectorizer(analyzer='char')
X_train_feat = vectorizer.fit_transform(X_train)
print(X_train_feat.shape)
print(vectorizer.get_feature_names()[:10], '...', vectorizer.get_feature_names()[-10:])

(1422, 85)
['\x03', '\x06', '\x08', '\t', '\n', '\x1a', '\x1b', ' ', '!', '"'] ... ['~', '³', 'ß', 'å', 'é', 'í', '÷', 'û', 'ý', 'ÿ']
