In [12]:
!pwd

/home/ubuntu/Berend_Gort


In [13]:
%run imports.py

%cat imports.py


import pandas as pd
import numpy as np

In [14]:
pokemon_df = pd.read_csv('Pokemon_m.csv', index_col=0, encoding='utf-8')
pokemon_df

Name    Type_1   Type_2  Total   HP  Attack  Defense  Sp_Atk  \
#                                                                         
1     Bulbasaur     Grass   Poison    318   45      49       49      65   
2       Ivysaur     Grass   Poison    405   60      62       63      80   
3      Venusaur     Grass   Poison    525   80      82       83     100   
4    Charmander      Fire      NaN    309   39      52       43      60   
5    Charmeleon      Fire      NaN    405   58      64       58      80   
6     Charizard      Fire   Flying    534   78      84       78     109   
7      Squirtle     Water      NaN    314   44      48       65      50   
8     Wartortle     Water      NaN    405   59      63       80      65   
9     Blastoise     Water      NaN    530   79      83      100      85   
10     Caterpie       Bug      NaN    195   45      30       35      20   
11      Metapod       Bug      NaN    205   50      20       55      25   
12   Butterfree       Bug   Flying    395   60      45       50      90   
13       Weedle       Bug   Poison    195   40      35       30      20   
14       Kakuna       Bug   Poison    205   45      25       50      25   
15     Beedrill       Bug   Poison    395   65      90       40      45   
16       Pidgey    Normal   Flying    251   40      45       40      35   
17    Pidgeotto    Normal   Flying    349   63      60       55      50   
18      Pidgeot    Normal   Flying    479   83      80       75      70   
19      Rattata    Normal      NaN    253   30      56       35      25   
20     Raticate    Normal      NaN    413   55      81       60      50   
21      Spearow    Normal   Flying    262   40      60       30      31   
22       Fearow    Normal   Flying    442   65      90       65      61   
23        Ekans    Poison      NaN    288   35      60       44      40   
24        Arbok    Poison      NaN    438   60      85       69      65   
25      Pikachu  Electric      NaN    320   35      55       40      50   
26       Raichu  Electric      NaN    485   60      90       55      90   
27    Sandshrew    Ground      NaN    300   50      75       85      20   
28    Sandslash    Ground      NaN    450   75     100      110      45   
29   Nidoran‰ªÛ    Poison      NaN    275   55      47       52      40   
30     Nidorina    Poison      NaN    365   70      62       67      55   
..          ...       ...      ...    ...  ...     ...      ...     ...   
122    Mr. Mime   Psychic    Fairy    460   40      45       65     100   
123     Scyther       Bug   Flying    500   70     110       80      55   
124        Jynx       Ice  Psychic    455   65      50       35     115   
125  Electabuzz  Electric      NaN    490   65      83       57      95   
126      Magmar      Fire      NaN    495   65      95       57     100   
127      Pinsir       Bug      NaN    500   65     125      100      55   
128      Tauros    Normal      NaN    490   75     100       95      40   
129    Magikarp     Water      NaN    200   20      10       55      15   
130    Gyarados     Water   Flying    540   95     125       79      60   
131      Lapras     Water      Ice    535  130      85       80      85   
132       Ditto    Normal      NaN    288   48      48       48      48   
133       Eevee    Normal      NaN    325   55      55       50      45   
134    Vaporeon     Water      NaN    525  130      65       60     110   
135     Jolteon  Electric      NaN    525   65      65       60     110   
136     Flareon      Fire      NaN    525   65     130       60      95   
137     Porygon    Normal      NaN    395   65      60       70      85   
138     Omanyte      Rock    Water    355   35      40      100      90   
139     Omastar      Rock    Water    495   70      60      125     115   
140      Kabuto      Rock    Water    355   30      80       90      55   
141    Kabutops      Rock    Water    495   60     115      105      65   
142  Aerodactyl      Rock   Flying  

In [15]:
import sklearn
from sklearn import datasets
from sklearn import preprocessing
from sklearn import metrics
from sklearn import model_selection
from sklearn.pipeline import Pipeline
from sklearn.feature_selection  import *
from sklearn.linear_model  import *

#### custom transformer

In [17]:
transformer = preprocessing.FunctionTransformer(lambda x: x+17)
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([[17, 18],
       [19, 20]])

In [21]:
def my_functional_transformer_function(X):
    
    print(X)
    return X + 17

In [22]:
transformer = preprocessing.FunctionTransformer(my_functional_transformer_function)
transformer.transform(pokemon_df[ ['HP', 'Attack' , 'Defense'] ])

[[ 45  49  49]
 [ 60  62  63]
 [ 80  82  83]
 [ 39  52  43]
 [ 58  64  58]
 [ 78  84  78]
 [ 44  48  65]
 [ 59  63  80]
 [ 79  83 100]
 [ 45  30  35]
 [ 50  20  55]
 [ 60  45  50]
 [ 40  35  30]
 [ 45  25  50]
 [ 65  90  40]
 [ 40  45  40]
 [ 63  60  55]
 [ 83  80  75]
 [ 30  56  35]
 [ 55  81  60]
 [ 40  60  30]
 [ 65  90  65]
 [ 35  60  44]
 [ 60  85  69]
 [ 35  55  40]
 [ 60  90  55]
 [ 50  75  85]
 [ 75 100 110]
 [ 55  47  52]
 [ 70  62  67]
 [ 90  92  87]
 [ 46  57  40]
 [ 61  72  57]
 [ 81 102  77]
 [ 70  45  48]
 [ 95  70  73]
 [ 38  41  40]
 [ 73  76  75]
 [115  45  20]
 [140  70  45]
 [ 40  45  35]
 [ 75  80  70]
 [ 45  50  55]
 [ 60  65  70]
 [ 75  80  85]
 [ 35  70  55]
 [ 60  95  80]
 [ 60  55  50]
 [ 70  65  60]
 [ 10  55  25]
 [ 35  80  50]
 [ 40  45  35]
 [ 65  70  60]
 [ 50  52  48]
 [ 80  82  78]
 [ 40  80  35]
 [ 65 105  60]
 [ 55  70  45]
 [ 90 110  80]
 [ 40  50  40]
 [ 65  65  65]
 [ 90  95  95]
 [ 25  20  15]
 [ 40  35  30]
 [ 55  50  45]
 [ 70  80  50]
 [ 80 100 

array([[ 62,  66,  66],
       [ 77,  79,  80],
       [ 97,  99, 100],
       [ 56,  69,  60],
       [ 75,  81,  75],
       [ 95, 101,  95],
       [ 61,  65,  82],
       [ 76,  80,  97],
       [ 96, 100, 117],
       [ 62,  47,  52],
       [ 67,  37,  72],
       [ 77,  62,  67],
       [ 57,  52,  47],
       [ 62,  42,  67],
       [ 82, 107,  57],
       [ 57,  62,  57],
       [ 80,  77,  72],
       [100,  97,  92],
       [ 47,  73,  52],
       [ 72,  98,  77],
       [ 57,  77,  47],
       [ 82, 107,  82],
       [ 52,  77,  61],
       [ 77, 102,  86],
       [ 52,  72,  57],
       [ 77, 107,  72],
       [ 67,  92, 102],
       [ 92, 117, 127],
       [ 72,  64,  69],
       [ 87,  79,  84],
       [107, 109, 104],
       [ 63,  74,  57],
       [ 78,  89,  74],
       [ 98, 119,  94],
       [ 87,  62,  65],
       [112,  87,  90],
       [ 55,  58,  57],
       [ 90,  93,  92],
       [132,  62,  37],
       [157,  87,  62],
       [ 57,  62,  52],
       [ 92,  97

#### fullscale partial transformer

In [23]:
from sklearn.base import TransformerMixin

In [168]:
class FunctionFeaturizer(TransformerMixin):
    def __init__(self, *featurizers, seventeen=17):
        self.seventeen = seventeen

    def fit(self, X, y=None):
        self.seventeen = - np.mean(X)
        return self

    def transform(self, X):
        #Do transformations
        return X+self.seventeen


In [169]:
our_transformer = FunctionFeaturizer(seventeen=19)
X = np.array([[0, 1], [2, 3]])
our_transformer.transform(X)


array([[19, 20],
       [21, 22]])

In [175]:
our_fit_transformer = our_transformer.fit(X)
our_fit_transformer

In [173]:
our_fit_transformer.transform(X)

array([[-1.5, -0.5],
       [ 0.5,  1.5]])

In [37]:
our_fit_transformer.transform(X).mean()

0.0

In [39]:
our_fit_transformer

In [38]:
our_fit_transformer.seventeen

-1.5

#### Exercise 5.1: Write a fucntional transformer that computes string of all variables in the row

In [65]:
bulbasaur = pokemon_df.iloc[0,:]
str(bulbasaur[7])

'65'

In [77]:
def my_functional_transformer_function(sample):
    string = ''
    for i in range(len(sample)):
      piece = str(sample[i])
      string = string + ' ' + piece    
    return string

In [80]:
my_functional_transformer_function(bulbasaur)

' Bulbasaur Grass Poison 318 45 49 49 65 65 45 1 False'

In [94]:
string_of_all_rows = [pokemon_df.shape[0],1]
string_of_all_rows

[151, 1]

In [96]:
string_of_all_rows = [pokemon_df.shape[0],1]
for i in range(pokemon_df.shape[0]):
    pokemon_i = pokemon_df.iloc[i,:]
    string_of_all_rows.append(my_functional_transformer_function(pokemon_i))
string_of_all_rows

[151,
 1,
 ' Bulbasaur Grass Poison 318 45 49 49 65 65 45 1 False',
 ' Ivysaur Grass Poison 405 60 62 63 80 80 60 2 False',
 ' Venusaur Grass Poison 525 80 82 83 100 100 80 3 False',
 ' Charmander Fire nan 309 39 52 43 60 50 65 1 False',
 ' Charmeleon Fire nan 405 58 64 58 80 65 80 2 False',
 ' Charizard Fire Flying 534 78 84 78 109 85 100 3 False',
 ' Squirtle Water nan 314 44 48 65 50 64 43 1 False',
 ' Wartortle Water nan 405 59 63 80 65 80 58 2 False',
 ' Blastoise Water nan 530 79 83 100 85 105 78 3 False',
 ' Caterpie Bug nan 195 45 30 35 20 20 45 1 False',
 ' Metapod Bug nan 205 50 20 55 25 25 30 2 False',
 ' Butterfree Bug Flying 395 60 45 50 90 80 70 3 False',
 ' Weedle Bug Poison 195 40 35 30 20 20 50 1 False',
 ' Kakuna Bug Poison 205 45 25 50 25 25 35 2 False',
 ' Beedrill Bug Poison 395 65 90 40 45 80 75 3 False',
 ' Pidgey Normal Flying 251 40 45 40 35 35 56 1 False',
 ' Pidgeotto Normal Flying 349 63 60 55 50 50 71 2 False',
 ' Pidgeot Normal Flying 479 83 80 75 70 70 10

#### Exercise 5.2: Write a custom transformer for titanic dataset that extracts Mrs. from the name of passegner

In [97]:
titanic_df = pd.read_csv('titanic.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [128]:
list_of_names = titanic_df['Name']
list_of_names[0]

res = list_of_names[8].split() 

res

#res == 'Mrs.'

['Johnson,', 'Mrs.', 'Oscar', 'W', '(Elisabeth', 'Vilhelmina', 'Berg)']

In [142]:
import re

def my_functional_transformer_function(name): 
    separate_strings= name.split()   
    for i in range(len(separate_strings)):
        if separate_strings[i] == 'Mrs.':
            index_Mrs = i
        else:
            pass      
    return print('In the name |', name, '| the', index_Mrs + 1 ,'nd', 'word contains Mrs.')


In [143]:
my_functional_transformer_function(list_of_names[8])

In the name | Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg) | the 2 nd word contains Mrs.


#### custom classifier

In [144]:
from sklearn.base import BaseEstimator, ClassifierMixin

In [167]:
class MyClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self, lr=0.2):
        pass
        
    def fit(self, X, y):
        pass

    def predict(self, X):
    
        pass

#### Exercise 5.3: Write a custom classifer that scans training dataset, computes average values and outputs it as prediction

In [153]:
pokemon_df

Name    Type_1   Type_2  Total   HP  Attack  Defense  Sp_Atk  \
#                                                                         
1     Bulbasaur     Grass   Poison    318   45      49       49      65   
2       Ivysaur     Grass   Poison    405   60      62       63      80   
3      Venusaur     Grass   Poison    525   80      82       83     100   
4    Charmander      Fire      NaN    309   39      52       43      60   
5    Charmeleon      Fire      NaN    405   58      64       58      80   
6     Charizard      Fire   Flying    534   78      84       78     109   
7      Squirtle     Water      NaN    314   44      48       65      50   
8     Wartortle     Water      NaN    405   59      63       80      65   
9     Blastoise     Water      NaN    530   79      83      100      85   
10     Caterpie       Bug      NaN    195   45      30       35      20   
11      Metapod       Bug      NaN    205   50      20       55      25   
12   Butterfree       Bug   Flying    395   60      45       50      90   
13       Weedle       Bug   Poison    195   40      35       30      20   
14       Kakuna       Bug   Poison    205   45      25       50      25   
15     Beedrill       Bug   Poison    395   65      90       40      45   
16       Pidgey    Normal   Flying    251   40      45       40      35   
17    Pidgeotto    Normal   Flying    349   63      60       55      50   
18      Pidgeot    Normal   Flying    479   83      80       75      70   
19      Rattata    Normal      NaN    253   30      56       35      25   
20     Raticate    Normal      NaN    413   55      81       60      50   
21      Spearow    Normal   Flying    262   40      60       30      31   
22       Fearow    Normal   Flying    442   65      90       65      61   
23        Ekans    Poison      NaN    288   35      60       44      40   
24        Arbok    Poison      NaN    438   60      85       69      65   
25      Pikachu  Electric      NaN    320   35      55       40      50   
26       Raichu  Electric      NaN    485   60      90       55      90   
27    Sandshrew    Ground      NaN    300   50      75       85      20   
28    Sandslash    Ground      NaN    450   75     100      110      45   
29   Nidoran‰ªÛ    Poison      NaN    275   55      47       52      40   
30     Nidorina    Poison      NaN    365   70      62       67      55   
..          ...       ...      ...    ...  ...     ...      ...     ...   
122    Mr. Mime   Psychic    Fairy    460   40      45       65     100   
123     Scyther       Bug   Flying    500   70     110       80      55   
124        Jynx       Ice  Psychic    455   65      50       35     115   
125  Electabuzz  Electric      NaN    490   65      83       57      95   
126      Magmar      Fire      NaN    495   65      95       57     100   
127      Pinsir       Bug      NaN    500   65     125      100      55   
128      Tauros    Normal      NaN    490   75     100       95      40   
129    Magikarp     Water      NaN    200   20      10       55      15   
130    Gyarados     Water   Flying    540   95     125       79      60   
131      Lapras     Water      Ice    535  130      85       80      85   
132       Ditto    Normal      NaN    288   48      48       48      48   
133       Eevee    Normal      NaN    325   55      55       50      45   
134    Vaporeon     Water      NaN    525  130      65       60     110   
135     Jolteon  Electric      NaN    525   65      65       60     110   
136     Flareon      Fire      NaN    525   65     130       60      95   
137     Porygon    Normal      NaN    395   65      60       70      85   
138     Omanyte      Rock    Water    355   35      40      100      90   
139     Omastar      Rock    Water    495   70      60      125     115   
140      Kabuto      Rock    Water    355   30      80       90      55   
141    Kabutops      Rock    Water    495   60     115      105      65   
142  Aerodactyl      Rock   Flying  

In [162]:

numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
pokemon_df_numeric = pokemon_df.select_dtypes(include=numerics)
pokemon_df_numeric

Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Stage
#                                                             
1      318   45      49       49      65      65     45      1
2      405   60      62       63      80      80     60      2
3      525   80      82       83     100     100     80      3
4      309   39      52       43      60      50     65      1
5      405   58      64       58      80      65     80      2
6      534   78      84       78     109      85    100      3
7      314   44      48       65      50      64     43      1
8      405   59      63       80      65      80     58      2
9      530   79      83      100      85     105     78      3
10     195   45      30       35      20      20     45      1
11     205   50      20       55      25      25     30      2
12     395   60      45       50      90      80     70      3
13     195   40      35       30      20      20     50      1
14     205   45      25       50      25      25     35      2
15     395   65      90       40      45      80     75      3
16     251   40      45       40      35      35     56      1
17     349   63      60       55      50      50     71      2
18     479   83      80       75      70      70    101      3
19     253   30      56       35      25      35     72      1
20     413   55      81       60      50      70     97      2
21     262   40      60       30      31      31     70      1
22     442   65      90       65      61      61    100      2
23     288   35      60       44      40      54     55      1
24     438   60      85       69      65      79     80      2
25     320   35      55       40      50      50     90      1
26     485   60      90       55      90      80    110      2
27     300   50      75       85      20      30     40      1
28     450   75     100      110      45      55     65      2
29     275   55      47       52      40      40     41      1
30     365   70      62       67      55      55     56      2
..     ...  ...     ...      ...     ...     ...    ...    ...
122    460   40      45       65     100     120     90      1
123    500   70     110       80      55      80    105      1
124    455   65      50       35     115      95     95      1
125    490   65      83       57      95      85    105      1
126    495   65      95       57     100      85     93      1
127    500   65     125      100      55      70     85      1
128    490   75     100       95      40      70    110      1
129    200   20      10       55      15      20     80      1
130    540   95     125       79      60     100     81      2
131    535  130      85       80      85      95     60      1
132    288   48      48       48      48      48     48      1
133    325   55      55       50      45      65     55      1
134    525  130      65       60     110      95     65      2
135    525   65      65       60     110      95    130      2
136    525   65     130       60      95     110     65      2
137    395   65      60       70      85      75     40      1
138    355   35      40      100      90      55     35      1
139    495   70      60      125     115      70     55      2
140    355   30      80       90      55      45     55      1
141    495   60     115      105      65      70     80      2
142    515   80     105       65      60      75    130      1
143    540  160     110       65      65     110     30      1
144    580   90      85      100      95     125     85      1
145    580   90      90       85     125      90    100      1
146    580   90     100       90     125      85     90      1
147    300   41      64       45      50      50     50      1
148    420   61      84       65      70      70     70      2
149    600   91     134       95     100     100     80      3
150    680  106     110       90     154      90    130      1
151    600  100     100      100     100     100    100      1

[151 rows x 8 columns]

In [144]:
from sklearn.base import BaseEstimator, ClassifierMixin

In [197]:
class MyClass:  
    def __init__(self, my_dataframe):
        numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64'] 
        self.my_dataframe = my_dataframe
        self.numeric_df = self.my_dataframe.select_dtypes(include=numerics)  
        
    def fit(self, X, y):
        pass

    def predict(self, X):
        pass

In [199]:
a = MyClass(pokemon_df)
a.numeric_df

Total   HP  Attack  Defense  Sp_Atk  Sp_Def  Speed  Stage
#                                                             
1      318   45      49       49      65      65     45      1
2      405   60      62       63      80      80     60      2
3      525   80      82       83     100     100     80      3
4      309   39      52       43      60      50     65      1
5      405   58      64       58      80      65     80      2
6      534   78      84       78     109      85    100      3
7      314   44      48       65      50      64     43      1
8      405   59      63       80      65      80     58      2
9      530   79      83      100      85     105     78      3
10     195   45      30       35      20      20     45      1
11     205   50      20       55      25      25     30      2
12     395   60      45       50      90      80     70      3
13     195   40      35       30      20      20     50      1
14     205   45      25       50      25      25     35      2
15     395   65      90       40      45      80     75      3
16     251   40      45       40      35      35     56      1
17     349   63      60       55      50      50     71      2
18     479   83      80       75      70      70    101      3
19     253   30      56       35      25      35     72      1
20     413   55      81       60      50      70     97      2
21     262   40      60       30      31      31     70      1
22     442   65      90       65      61      61    100      2
23     288   35      60       44      40      54     55      1
24     438   60      85       69      65      79     80      2
25     320   35      55       40      50      50     90      1
26     485   60      90       55      90      80    110      2
27     300   50      75       85      20      30     40      1
28     450   75     100      110      45      55     65      2
29     275   55      47       52      40      40     41      1
30     365   70      62       67      55      55     56      2
..     ...  ...     ...      ...     ...     ...    ...    ...
122    460   40      45       65     100     120     90      1
123    500   70     110       80      55      80    105      1
124    455   65      50       35     115      95     95      1
125    490   65      83       57      95      85    105      1
126    495   65      95       57     100      85     93      1
127    500   65     125      100      55      70     85      1
128    490   75     100       95      40      70    110      1
129    200   20      10       55      15      20     80      1
130    540   95     125       79      60     100     81      2
131    535  130      85       80      85      95     60      1
132    288   48      48       48      48      48     48      1
133    325   55      55       50      45      65     55      1
134    525  130      65       60     110      95     65      2
135    525   65      65       60     110      95    130      2
136    525   65     130       60      95     110     65      2
137    395   65      60       70      85      75     40      1
138    355   35      40      100      90      55     35      1
139    495   70      60      125     115      70     55      2
140    355   30      80       90      55      45     55      1
141    495   60     115      105      65      70     80      2
142    515   80     105       65      60      75    130      1
143    540  160     110       65      65     110     30      1
144    580   90      85      100      95     125     85      1
145    580   90      90       85     125      90    100      1
146    580   90     100       90     125      85     90      1
147    300   41      64       45      50      50     50      1
148    420   61      84       65      70      70     70      2
149    600   91     134       95     100     100     80      3
150    680  106     110       90     154      90    130      1
151    600  100     100      100     100     100    100      1

[151 rows x 8 columns]

#### Exercise 5.4: Write custom transofrmer that extracts only string features

In [101]:
class FunctionFeaturizer(TransformerMixin):
    def __init__(self, *featurizers, seventeen=17):
        self.seventeen = seventeen

    def fit(self, X, y=None):
        self.feature_type = type(X)
        return self

    def transform(self, X):
        #Do transformations
        if self.feature_type == str:
            return X


#### Exercise 5.5: Write custom transofrmer that extracts only float features